<?php

namespace Trainee\Database;

use Trainee\Database\om\BaseAlbumQuery;


/**
 * Skeleton subclass for performing query and update operations on the 'trainee_orm_propel1album' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Fri Sep  5 00:00:18 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.
 */
class AlbumQuery extends BaseAlbumQuery
{
}
