<?php

namespace Trainee\Database\om;

use \Criteria;
use \Exception;
use \ModelCriteria;
use \ModelJoin;
use \PDO;
use \Propel;
use \PropelCollection;
use \PropelException;
use \PropelObjectCollection;
use \PropelPDO;
use Trainee\Database\Album;
use Trainee\Database\AlbumPeer;
use Trainee\Database\AlbumQuery;
use Trainee\Database\Interpret;

/**
 * Base class that represents a query for the 'trainee_orm_propel1album' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Fri 05 Sep 2014 03:55:42 PM CEST
 *
 * @method AlbumQuery orderById($order = Criteria::ASC) Order by the id column
 * @method AlbumQuery orderByInterpretId($order = Criteria::ASC) Order by the interpret_id column
 * @method AlbumQuery orderByTitle($order = Criteria::ASC) Order by the title column
 * @method AlbumQuery orderByNumberOfTracks($order = Criteria::ASC) Order by the number_of_tracks column
 *
 * @method AlbumQuery groupById() Group by the id column
 * @method AlbumQuery groupByInterpretId() Group by the interpret_id column
 * @method AlbumQuery groupByTitle() Group by the title column
 * @method AlbumQuery groupByNumberOfTracks() Group by the number_of_tracks column
 *
 * @method AlbumQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method AlbumQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method AlbumQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method AlbumQuery leftJoinInterpret($relationAlias = null) Adds a LEFT JOIN clause to the query using the Interpret relation
 * @method AlbumQuery rightJoinInterpret($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Interpret relation
 * @method AlbumQuery innerJoinInterpret($relationAlias = null) Adds a INNER JOIN clause to the query using the Interpret relation
 *
 * @method Album findOne(PropelPDO $con = null) Return the first Album matching the query
 * @method Album findOneOrCreate(PropelPDO $con = null) Return the first Album matching the query, or a new Album object populated from the query conditions when no match is found
 *
 * @method Album findOneById(int $id) Return the first Album filtered by the id column
 * @method Album findOneByInterpretId(int $interpret_id) Return the first Album filtered by the interpret_id column
 * @method Album findOneByTitle(string $title) Return the first Album filtered by the title column
 * @method Album findOneByNumberOfTracks(int $number_of_tracks) Return the first Album filtered by the number_of_tracks column
 *
 * @method array findById(int $id) Return Album objects filtered by the id column
 * @method array findByInterpretId(int $interpret_id) Return Album objects filtered by the interpret_id column
 * @method array findByTitle(string $title) Return Album objects filtered by the title column
 * @method array findByNumberOfTracks(int $number_of_tracks) Return Album objects filtered by the number_of_tracks column
 *
 * @package    propel.generator..om
 */
abstract class BaseAlbumQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseAlbumQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = null, $modelName = null, $modelAlias = null)
    {
        if (null === $dbName) {
            $dbName = 'trainee_database';
        }
        if (null === $modelName) {
            $modelName = 'Trainee\\Database\\Album';
        }
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new AlbumQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param   AlbumQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return AlbumQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof AlbumQuery) {
            return $criteria;
        }
        $query = new AlbumQuery(null, null, $modelAlias);

        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj = $c->findPk(array(12, 34), $con);
     * </code>
     *
     * @param array $key Primary key to use for the query
                         A Primary key composition: [$id, $interpret_id]
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Album|Album[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = AlbumPeer::getInstanceFromPool(serialize(array((string) $key[0], (string) $key[1]))))) && !$this->formatter) {
            // the object is already in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(AlbumPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 Album A model object, or null if the key is not found
     * @throws PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT id, interpret_id, title, number_of_tracks FROM trainee_orm_propel1album WHERE id = :p0 AND interpret_id = :p1';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key[0], PDO::PARAM_INT);
            $stmt->bindValue(':p1', $key[1], PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Album();
            $obj->hydrate($row);
            AlbumPeer::addInstanceToPool($obj, serialize(array((string) $key[0], (string) $key[1])));
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Album|Album[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(array(12, 56), array(832, 123), array(123, 456)), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Album[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return AlbumQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {
        $this->addUsingAlias(AlbumPeer::ID, $key[0], Criteria::EQUAL);
        $this->addUsingAlias(AlbumPeer::INTERPRET_ID, $key[1], Criteria::EQUAL);

        return $this;
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return AlbumQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {
        if (empty($keys)) {
            return $this->add(null, '1<>1', Criteria::CUSTOM);
        }
        foreach ($keys as $key) {
            $cton0 = $this->getNewCriterion(AlbumPeer::ID, $key[0], Criteria::EQUAL);
            $cton1 = $this->getNewCriterion(AlbumPeer::INTERPRET_ID, $key[1], Criteria::EQUAL);
            $cton0->addAnd($cton1);
            $this->addOr($cton0);
        }

        return $this;
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id >= 12
     * $query->filterById(array('max' => 12)); // WHERE id <= 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return AlbumQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id)) {
            $useMinMax = false;
            if (isset($id['min'])) {
                $this->addUsingAlias(AlbumPeer::ID, $id['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($id['max'])) {
                $this->addUsingAlias(AlbumPeer::ID, $id['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(AlbumPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the interpret_id column
     *
     * Example usage:
     * <code>
     * $query->filterByInterpretId(1234); // WHERE interpret_id = 1234
     * $query->filterByInterpretId(array(12, 34)); // WHERE interpret_id IN (12, 34)
     * $query->filterByInterpretId(array('min' => 12)); // WHERE interpret_id >= 12
     * $query->filterByInterpretId(array('max' => 12)); // WHERE interpret_id <= 12
     * </code>
     *
     * @see       filterByInterpret()
     *
     * @param     mixed $interpretId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return AlbumQuery The current query, for fluid interface
     */
    public function filterByInterpretId($interpretId = null, $comparison = null)
    {
        if (is_array($interpretId)) {
            $useMinMax = false;
            if (isset($interpretId['min'])) {
                $this->addUsingAlias(AlbumPeer::INTERPRET_ID, $interpretId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($interpretId['max'])) {
                $this->addUsingAlias(AlbumPeer::INTERPRET_ID, $interpretId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(AlbumPeer::INTERPRET_ID, $interpretId, $comparison);
    }

    /**
     * Filter the query on the title column
     *
     * Example usage:
     * <code>
     * $query->filterByTitle('fooValue');   // WHERE title = 'fooValue'
     * $query->filterByTitle('%fooValue%'); // WHERE title LIKE '%fooValue%'
     * </code>
     *
     * @param     string $title The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return AlbumQuery The current query, for fluid interface
     */
    public function filterByTitle($title = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($title)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $title)) {
                $title = str_replace('*', '%', $title);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(AlbumPeer::TITLE, $title, $comparison);
    }

    /**
     * Filter the query on the number_of_tracks column
     *
     * Example usage:
     * <code>
     * $query->filterByNumberOfTracks(1234); // WHERE number_of_tracks = 1234
     * $query->filterByNumberOfTracks(array(12, 34)); // WHERE number_of_tracks IN (12, 34)
     * $query->filterByNumberOfTracks(array('min' => 12)); // WHERE number_of_tracks >= 12
     * $query->filterByNumberOfTracks(array('max' => 12)); // WHERE number_of_tracks <= 12
     * </code>
     *
     * @param     mixed $numberOfTracks The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return AlbumQuery The current query, for fluid interface
     */
    public function filterByNumberOfTracks($numberOfTracks = null, $comparison = null)
    {
        if (is_array($numberOfTracks)) {
            $useMinMax = false;
            if (isset($numberOfTracks['min'])) {
                $this->addUsingAlias(AlbumPeer::NUMBER_OF_TRACKS, $numberOfTracks['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($numberOfTracks['max'])) {
                $this->addUsingAlias(AlbumPeer::NUMBER_OF_TRACKS, $numberOfTracks['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(AlbumPeer::NUMBER_OF_TRACKS, $numberOfTracks, $comparison);
    }

    /**
     * Filter the query by a related Interpret object
     *
     * @param   Interpret|PropelObjectCollection $interpret The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 AlbumQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByInterpret($interpret, $comparison = null)
    {
        if ($interpret instanceof Interpret) {
            return $this
                ->addUsingAlias(AlbumPeer::INTERPRET_ID, $interpret->getId(), $comparison);
        } elseif ($interpret instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(AlbumPeer::INTERPRET_ID, $interpret->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByInterpret() only accepts arguments of type Interpret or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Interpret relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return AlbumQuery The current query, for fluid interface
     */
    public function joinInterpret($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Interpret');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Interpret');
        }

        return $this;
    }

    /**
     * Use the Interpret relation Interpret object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   \Trainee\Database\InterpretQuery A secondary query class using the current class as primary query
     */
    public function useInterpretQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinInterpret($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Interpret', '\Trainee\Database\InterpretQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   Album $album Object to remove from the list of results
     *
     * @return AlbumQuery The current query, for fluid interface
     */
    public function prune($album = null)
    {
        if ($album) {
            $this->addCond('pruneCond0', $this->getAliasedColName(AlbumPeer::ID), $album->getId(), Criteria::NOT_EQUAL);
            $this->addCond('pruneCond1', $this->getAliasedColName(AlbumPeer::INTERPRET_ID), $album->getInterpretId(), Criteria::NOT_EQUAL);
            $this->combine(array('pruneCond0', 'pruneCond1'), Criteria::LOGICAL_OR);
        }

        return $this;
    }

}
